### ISSUE TITLE
repo_ca_dir rather than repo_ca_cert?

### ISSUE THREAD

**Issue by jcpunk** [candlepin/subscription-manager#1415]
Currently /etc/rhsm/rhsm.conf supports:
productCertDir
entitlementCertDir
consumerCertDir

But for the Repo CA Cert, I've got to specify a specific filename.  Any chance the repo could support searching a directory of CA certs so that the exact path to the CA file need not be hard coded?

**Comment by awood** [comment]
@jcpunk the file that `repo_ca_cert` points to by default (`/etc/rhsm/ca/redhat_uep.pem`) is actually a bundle of multiple CA certificates concatenated together.  Just as a quick fix to address your need, you could try appending the CA certificate you need onto the end of that file and see if that works.

That configuration value is ultimately just passed off to yum to use in the `sslcacert` configuration.  According to the yum.conf man page, this value can accept a directory.  So you could also just try setting that value to point to a directory instead of a file.  If my reading of the code is correct, subscription-manager will just copy that value over to the resultant repo files.  (We never actually use the value to set up our own TLS connection or anything).

Let me know if either of those two options work for you.  If the second option works, we can just update our man page to reflect that a directory is an acceptable value.

**Comment by jcpunk** [comment]
Option A (cat the files together) seems to get it rolling.

Alas Option B seems to result in  [Errno 14] curl#77 - "Problem with the SSL CA cert (path? access rights?)" on EL7.

**Comment by awood** [comment]
Would you mind trying one last experiment for me?  Temporarily alter the `sslcacert` for a repo in `redhat.repo` file to point to the directory holding the `repo_ca_cert`.  And then run a `yum clean all && yum repolist`.  Those commands should force yum to re-download all the repo metadata and any issue with the TLS connection would manifest at that point.

I am wagering that you will get the same "Problem with the SSL CA cert" issue.  If you do, then unfortunately there's not much that subscription-manager can do since we're restricted by what yum will recognize.

**Comment by jcpunk** [comment]
Alas, the behavior repeats.

**Comment by awood** [comment]
Okay, I'm going to close this issue since it's an underlying problem/lack-of-feature with yum.  Hopefully the concatenating onto `redhat_uep.pem` will be an adequate solution.  If not, I recommend filing an issue against yum.  In my opinion it does seem like a bug in yum since the man page for yum.conf reads "sslcacert - Path to the **directory** containing the databases of the certificate authorities
yum should use to  verify  SSL  certificates. Defaults to none - uses system default" (emphasis mine).
